/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

import Conexion.ConexionDB;
import java.sql.Connection;
import java.awt.Color;
import javax.swing.JOptionPane;
import Conexion.ConexionDB;
import static Conexion.ConexionDB.obtenerConexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;

/**
 *
 * @author Usuario
 */
public class NuevoUsu extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsu
     */
    public NuevoUsu() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(FondoText, "src/Img/Fondo.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(PerfilMasText, "src/Img/PerfilMas.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Clases.PanelRound();
        PerfilMasText = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        CampoContraseña = new javax.swing.JPasswordField();
        NickContraseña = new javax.swing.JLabel();
        NickUsuario1 = new javax.swing.JLabel();
        CampoCorreo = new javax.swing.JTextField();
        NickContraseña1 = new javax.swing.JLabel();
        CampoDocumento = new javax.swing.JTextField();
        PanelAtras = new Clases.PanelRound();
        AtrasText = new javax.swing.JLabel();
        PanelRegistrar = new Clases.PanelRound();
        RegistrarText = new javax.swing.JLabel();
        NickUsuario2 = new javax.swing.JLabel();
        FondoText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(770, 480));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(770, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        PerfilMasText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Perfil.png"))); // NOI18N

        CampoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoUsuario.setForeground(new java.awt.Color(204, 204, 204));
        CampoUsuario.setText("Ingrese su usuario");
        CampoUsuario.setBorder(null);
        CampoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoUsuarioMousePressed(evt);
            }
        });
        CampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuarioActionPerformed(evt);
            }
        });

        CampoContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoContraseña.setForeground(new java.awt.Color(204, 204, 204));
        CampoContraseña.setText("**********");
        CampoContraseña.setBorder(null);
        CampoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoContraseñaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoContraseñaMousePressed(evt);
            }
        });

        NickContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NickContraseña.setText("CONTRASEÑA");

        NickUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NickUsuario1.setText("CORREO");

        CampoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoCorreo.setForeground(new java.awt.Color(204, 204, 204));
        CampoCorreo.setText("Ingrese su correo");
        CampoCorreo.setBorder(null);
        CampoCorreo.setInheritsPopupMenu(true);
        CampoCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoCorreoMousePressed(evt);
            }
        });
        CampoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCorreoActionPerformed(evt);
            }
        });

        NickContraseña1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NickContraseña1.setText("DOCUMENTO");

        CampoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoDocumento.setForeground(new java.awt.Color(204, 204, 204));
        CampoDocumento.setText("Ingrese su documento");
        CampoDocumento.setBorder(null);
        CampoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoDocumentoMousePressed(evt);
            }
        });
        CampoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDocumentoActionPerformed(evt);
            }
        });

        PanelAtras.setBackground(new java.awt.Color(102, 204, 255));
        PanelAtras.setRoundBottomLeft(30);
        PanelAtras.setRoundBottomRight(30);
        PanelAtras.setRoundTopLeft(30);
        PanelAtras.setRoundTopRight(30);
        PanelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelAtrasMouseExited(evt);
            }
        });

        AtrasText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AtrasText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AtrasText.setText("ATRAS");
        AtrasText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PanelAtrasLayout = new javax.swing.GroupLayout(PanelAtras);
        PanelAtras.setLayout(PanelAtrasLayout);
        PanelAtrasLayout.setHorizontalGroup(
            PanelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AtrasText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        PanelAtrasLayout.setVerticalGroup(
            PanelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AtrasText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        PanelRegistrar.setBackground(new java.awt.Color(102, 204, 255));
        PanelRegistrar.setRoundBottomLeft(30);
        PanelRegistrar.setRoundBottomRight(30);
        PanelRegistrar.setRoundTopLeft(30);
        PanelRegistrar.setRoundTopRight(30);
        PanelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseExited(evt);
            }
        });

        RegistrarText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegistrarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrarText.setText("REGISTRAR");
        RegistrarText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PanelRegistrarLayout = new javax.swing.GroupLayout(PanelRegistrar);
        PanelRegistrar.setLayout(PanelRegistrarLayout);
        PanelRegistrarLayout.setHorizontalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrarText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        PanelRegistrarLayout.setVerticalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrarText, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        NickUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NickUsuario2.setText("NOMBRE DE USUARIO");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(PanelAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(PanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(NickContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoContraseña))
                .addGap(30, 30, 30)
                .addComponent(PerfilMasText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CampoCorreo)
                    .addComponent(NickContraseña1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NickUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(NickUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGap(414, 414, 414)))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(CampoUsuario)
                                .addGap(28, 28, 28)
                                .addComponent(NickContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(NickUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoCorreo)
                                .addGap(28, 28, 28)
                                .addComponent(NickContraseña1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoDocumento)))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PerfilMasText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(72, 72, 72)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound1Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(NickUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(232, 232, 232)))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 630, 370));

        FondoText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo.jpg"))); // NOI18N
        jPanel1.add(FondoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 457));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoUsuarioMousePressed
        if(CampoUsuario.getText().equals("Ingrese su usuario")){
            CampoUsuario.setText("");
            CampoUsuario.setForeground(Color.black);
        }
        if(String.valueOf(CampoContraseña.getPassword()).isEmpty()){
            CampoContraseña.setText("**********");
            CampoContraseña.setForeground(Color.gray);
        }
        if(CampoCorreo.getText().isEmpty()){
            CampoCorreo.setText("Ingrese su correo");
            CampoCorreo.setForeground(Color.gray);
        }
        if(CampoDocumento.getText().isEmpty()){
            CampoDocumento.setText("Ingrese su documento");
            CampoDocumento.setForeground(Color.gray);
        }

    }//GEN-LAST:event_CampoUsuarioMousePressed

    private void CampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuarioActionPerformed

    private void CampoCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoCorreoMousePressed
        if(CampoUsuario.getText().isEmpty()){
            CampoUsuario.setText("Ingrese su usuario");
            CampoUsuario.setForeground(Color.gray);
        }
        if(String.valueOf(CampoContraseña.getPassword()).isEmpty()){
            CampoContraseña.setText("**********");
            CampoContraseña.setForeground(Color.gray);
        }
        if(CampoCorreo.getText().equals("Ingrese su correo")){
            CampoCorreo.setText("");
            CampoCorreo.setForeground(Color.black);
        }
        if(CampoDocumento.getText().isEmpty()){
            CampoDocumento.setText("Ingrese su documento");
            CampoDocumento.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CampoCorreoMousePressed

    private void CampoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCorreoActionPerformed

    private void CampoDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoDocumentoMousePressed
        if(CampoUsuario.getText().isEmpty()){
            CampoUsuario.setText("Ingrese su usuario");
            CampoUsuario.setForeground(Color.gray);
        }
        if(String.valueOf(CampoContraseña.getPassword()).isEmpty()){
            CampoContraseña.setText("**********");
            CampoContraseña.setForeground(Color.gray);
        }
        if(CampoCorreo.getText().isEmpty()){
            CampoCorreo.setText("Ingrese su correo");
            CampoCorreo.setForeground(Color.gray);
        }
        if(CampoDocumento.getText().equals("Ingrese su documento")){
            CampoDocumento.setText("");
            CampoDocumento.setForeground(Color.black);
        }
    }//GEN-LAST:event_CampoDocumentoMousePressed

    private void CampoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDocumentoActionPerformed

    private void CampoContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoContraseñaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoContraseñaMouseClicked

    private void CampoContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoContraseñaMousePressed
        if(CampoUsuario.getText().isEmpty()){
            CampoUsuario.setText("Ingrese su usuario");
            CampoUsuario.setForeground(Color.gray);
        }
        if(String.valueOf(CampoContraseña.getPassword()).equals("**********")){
            CampoContraseña.setText("");
            CampoContraseña.setForeground(Color.black);
        }
        if(CampoCorreo.getText().isEmpty()){
            CampoCorreo.setText("Ingrese su correo");
            CampoCorreo.setForeground(Color.gray);
        }
        if(CampoDocumento.getText().isEmpty()){
            CampoDocumento.setText("Ingrese su documento");
            CampoDocumento.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CampoContraseñaMousePressed

    private void PanelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAtrasMouseClicked
        Main newframe = new Main();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PanelAtrasMouseClicked

    private void PanelAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAtrasMouseEntered
        PanelAtras.setBackground(Color.blue);
    }//GEN-LAST:event_PanelAtrasMouseEntered

    private void PanelAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAtrasMouseExited
        PanelAtras.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_PanelAtrasMouseExited

    private void PanelRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseEntered
        PanelRegistrar.setBackground(Color.blue);
    }//GEN-LAST:event_PanelRegistrarMouseEntered

    private void PanelRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseExited
        PanelRegistrar.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_PanelRegistrarMouseExited

    private void PanelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseClicked
        String documentoStr = CampoDocumento.getText();
        String contraseña = String.valueOf(CampoContraseña.getPassword());
        String nombre = CampoUsuario.getText();
        String correo = CampoCorreo.getText();

        try{
            int documento = Integer.parseInt(documentoStr);
            String sql = "INSERT INTO Usuarios (documento, nombre, correo, contrasena) VALUES (?, ?, ?, ?)";
            Connection conn = (Connection) ConexionDB.obtenerConexion();
            // Conexión auto-cerrable (try-with-resources)
            try(PreparedStatement pstmt = conn.prepareStatement(sql)) {

                // Asignar valores a los parámetros
                pstmt.setInt(1, documento);
                pstmt.setString(2, nombre);
                pstmt.setString(3, correo);
                pstmt.setString(4, contraseña);

                // Ejecutar y verificar inserción
                int filasInsertadas = pstmt.executeUpdate();

                if (filasInsertadas > 0) {
                    JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente");
                    Sesion newframe = new Sesion();
                    newframe.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Documento debe ser solo números");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + ex.getMessage());
        }
    }//GEN-LAST:event_PanelRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NuevoUsu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AtrasText;
    private javax.swing.JPasswordField CampoContraseña;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoDocumento;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JLabel FondoText;
    private javax.swing.JLabel NickContraseña;
    private javax.swing.JLabel NickContraseña1;
    private javax.swing.JLabel NickUsuario1;
    private javax.swing.JLabel NickUsuario2;
    private Clases.PanelRound PanelAtras;
    private Clases.PanelRound PanelRegistrar;
    private javax.swing.JLabel PerfilMasText;
    private javax.swing.JLabel RegistrarText;
    private javax.swing.JPanel jPanel1;
    private Clases.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
