/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paquete;

import Conexion.ConexionDB;
import java.sql.Connection;
import java.awt.Color;
import javax.swing.JOptionPane;
import Conexion.ConexionDB;
import static Conexion.ConexionDB.obtenerConexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class NuevoAdmin extends javax.swing.JPanel {

    /**
     * Creates new form SalasAdmins
     */
    public NuevoAdmin() {
        DefaultTableModel model = new DefaultTableModel();
        initComponents();
        PerfilMasText.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            if (PerfilMasText.getWidth() > 0 && PerfilMasText.getHeight() > 0) {
                rsscalelabel.RSScaleLabel.setScaleLabel(PerfilMasText, "src/Img/PerfilMas.png");
                // Elimina el listener después de cargar la imagen una sola vez
                PerfilMasText.removeComponentListener(this);
            }
        }
    });
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Clases.PanelRound();
        PerfilMasText = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        CampoContraseña = new javax.swing.JPasswordField();
        NickContraseña = new javax.swing.JLabel();
        NickUsuario1 = new javax.swing.JLabel();
        CampoCorreo = new javax.swing.JTextField();
        NickContraseña1 = new javax.swing.JLabel();
        CampoDocumento = new javax.swing.JTextField();
        PanelRegistrar = new Clases.PanelRound();
        RegistrarText = new javax.swing.JLabel();
        NickUsuario2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(450, 430));
        setPreferredSize(new java.awt.Dimension(490, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        PerfilMasText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Perfil.png"))); // NOI18N

        CampoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoUsuario.setForeground(new java.awt.Color(204, 204, 204));
        CampoUsuario.setText("Ingrese su usuario");
        CampoUsuario.setBorder(null);
        CampoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoUsuarioMousePressed(evt);
            }
        });
        CampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuarioActionPerformed(evt);
            }
        });

        CampoContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoContraseña.setForeground(new java.awt.Color(204, 204, 204));
        CampoContraseña.setText("**********");
        CampoContraseña.setBorder(null);
        CampoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoContraseñaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoContraseñaMousePressed(evt);
            }
        });

        NickContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NickContraseña.setText("CONTRASEÑA");

        NickUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NickUsuario1.setText("CORREO");

        CampoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoCorreo.setForeground(new java.awt.Color(204, 204, 204));
        CampoCorreo.setText("Ingrese su correo");
        CampoCorreo.setBorder(null);
        CampoCorreo.setInheritsPopupMenu(true);
        CampoCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoCorreoMousePressed(evt);
            }
        });
        CampoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCorreoActionPerformed(evt);
            }
        });

        NickContraseña1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NickContraseña1.setText("DOCUMENTO");

        CampoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoDocumento.setForeground(new java.awt.Color(204, 204, 204));
        CampoDocumento.setText("Ingrese su documento");
        CampoDocumento.setBorder(null);
        CampoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoDocumentoMousePressed(evt);
            }
        });
        CampoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDocumentoActionPerformed(evt);
            }
        });

        PanelRegistrar.setBackground(new java.awt.Color(102, 204, 255));
        PanelRegistrar.setRoundBottomLeft(30);
        PanelRegistrar.setRoundBottomRight(30);
        PanelRegistrar.setRoundTopLeft(30);
        PanelRegistrar.setRoundTopRight(30);
        PanelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseExited(evt);
            }
        });

        RegistrarText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegistrarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrarText.setText("REGISTRAR");
        RegistrarText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PanelRegistrarLayout = new javax.swing.GroupLayout(PanelRegistrar);
        PanelRegistrar.setLayout(PanelRegistrarLayout);
        PanelRegistrarLayout.setHorizontalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrarText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelRegistrarLayout.setVerticalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrarText, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        NickUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NickUsuario2.setText("NOMBRE DE USUARIO");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(NickContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addComponent(NickUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CampoContraseña)
                        .addComponent(CampoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                .addGap(78, 78, 78)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NickUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NickContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(PerfilMasText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(PanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PerfilMasText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(NickUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoUsuario)
                        .addGap(28, 28, 28)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NickContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NickContraseña1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(NickUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoCorreo)
                        .addGap(48, 48, 48)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(CampoDocumento)
                        .addGap(75, 75, 75)))
                .addComponent(PanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void CampoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoUsuarioMousePressed
        if(CampoUsuario.getText().equals("Ingrese su usuario")){
            CampoUsuario.setText("");
            CampoUsuario.setForeground(Color.black);
        }
        if(String.valueOf(CampoContraseña.getPassword()).isEmpty()){
            CampoContraseña.setText("**********");
            CampoContraseña.setForeground(Color.gray);
        }
        if(CampoCorreo.getText().isEmpty()){
            CampoCorreo.setText("Ingrese su correo");
            CampoCorreo.setForeground(Color.gray);
        }
        if(CampoDocumento.getText().isEmpty()){
            CampoDocumento.setText("Ingrese su documento");
            CampoDocumento.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CampoUsuarioMousePressed

    private void CampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuarioActionPerformed

    private void CampoContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoContraseñaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoContraseñaMouseClicked

    private void CampoContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoContraseñaMousePressed
        if(CampoUsuario.getText().isEmpty()){
            CampoUsuario.setText("Ingrese su usuario");
            CampoUsuario.setForeground(Color.gray);
        }
        if(String.valueOf(CampoContraseña.getPassword()).equals("**********")){
            CampoContraseña.setText("");
            CampoContraseña.setForeground(Color.black);
        }
        if(CampoCorreo.getText().isEmpty()){
            CampoCorreo.setText("Ingrese su correo");
            CampoCorreo.setForeground(Color.gray);
        }
        if(CampoDocumento.getText().isEmpty()){
            CampoDocumento.setText("Ingrese su documento");
            CampoDocumento.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CampoContraseñaMousePressed

    private void CampoCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoCorreoMousePressed
        if(CampoUsuario.getText().isEmpty()){
            CampoUsuario.setText("Ingrese su usuario");
            CampoUsuario.setForeground(Color.gray);
        }
        if(String.valueOf(CampoContraseña.getPassword()).isEmpty()){
            CampoContraseña.setText("**********");
            CampoContraseña.setForeground(Color.gray);
        }
        if(CampoCorreo.getText().equals("Ingrese su correo")){
            CampoCorreo.setText("");
            CampoCorreo.setForeground(Color.black);
        }
        if(CampoDocumento.getText().isEmpty()){
            CampoDocumento.setText("Ingrese su documento");
            CampoDocumento.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CampoCorreoMousePressed

    private void CampoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCorreoActionPerformed

    private void CampoDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoDocumentoMousePressed
        if(CampoUsuario.getText().isEmpty()){
            CampoUsuario.setText("Ingrese su usuario");
            CampoUsuario.setForeground(Color.gray);
        }
        if(String.valueOf(CampoContraseña.getPassword()).isEmpty()){
            CampoContraseña.setText("**********");
            CampoContraseña.setForeground(Color.gray);
        }
        if(CampoCorreo.getText().isEmpty()){
            CampoCorreo.setText("Ingrese su correo");
            CampoCorreo.setForeground(Color.gray);
        }
        if(CampoDocumento.getText().equals("Ingrese su documento")){
            CampoDocumento.setText("");
            CampoDocumento.setForeground(Color.black);
        }
    }//GEN-LAST:event_CampoDocumentoMousePressed

    private void CampoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDocumentoActionPerformed

    private void PanelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseClicked
        String documentoStr = CampoDocumento.getText();
        String contraseña = String.valueOf(CampoContraseña.getPassword());
        String nombre = CampoUsuario.getText();
        String correo = CampoCorreo.getText();

        try {
            int documento = Integer.parseInt(documentoStr);

            // Verifica si el documento YA EXISTE
            String sqlVerificar = "SELECT documento FROM usuarios WHERE documento = ?";
            try (Connection con = ConexionDB.obtenerConexion();
                PreparedStatement ptmt = con.prepareStatement(sqlVerificar)) {

                ptmt.setInt(1, documento);
                try (ResultSet rs = ptmt.executeQuery()) {
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "El documento ya está registrado");
                        return;  // Detiene el proceso si ya existe
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(NuevoAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

            // 2. Si no existe, INSERTAR nuevo usuario
            String sqlInsert = "INSERT INTO Usuarios (documento, nombre, correo, contrasena, rol) VALUES (?, ?, ?, ?, 'admin')";
            try (Connection conn = ConexionDB.obtenerConexion();
                PreparedStatement pstmt = conn.prepareStatement(sqlInsert)) {

                pstmt.setInt(1, documento);
                pstmt.setString(2, nombre);
                pstmt.setString(3, correo);
                pstmt.setString(4, contraseña);

                int filasInsertadas = pstmt.executeUpdate();

                if (filasInsertadas > 0) {
                    JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente");
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Documento debe ser solo números");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + ex.getMessage());
        }
    }//GEN-LAST:event_PanelRegistrarMouseClicked

    private void PanelRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseEntered
        PanelRegistrar.setBackground(Color.blue);
    }//GEN-LAST:event_PanelRegistrarMouseEntered

    private void PanelRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseExited
        PanelRegistrar.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_PanelRegistrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CampoContraseña;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoDocumento;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JLabel NickContraseña;
    private javax.swing.JLabel NickContraseña1;
    private javax.swing.JLabel NickUsuario1;
    private javax.swing.JLabel NickUsuario2;
    private Clases.PanelRound PanelRegistrar;
    private javax.swing.JLabel PerfilMasText;
    private javax.swing.JLabel RegistrarText;
    private Clases.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables



    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
