/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class Sesion extends javax.swing.JFrame {

    /**
     * Creates new form Sesion
     */
    private int documento;
    public Sesion(int documento) {
        initComponents();
        this.documento = documento;
        this.setLocationRelativeTo(null);
        initSalas();
    }

    private Sesion() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        FondoPanel = new javax.swing.JPanel();
        panelRound1 = new Clases.PanelRound();
        panelRound2 = new Clases.PanelRound();
        PanelSala = new javax.swing.JPanel();
        TextSala1 = new javax.swing.JLabel();
        PanelReserva = new javax.swing.JPanel();
        TextReserva = new javax.swing.JLabel();
        PanelCambios = new javax.swing.JPanel();
        FondoText = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(770, 490));

        FondoPanel.setPreferredSize(new java.awt.Dimension(770, 480));
        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(102, 255, 255));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSala.setBackground(new java.awt.Color(153, 255, 255));
        PanelSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelSalaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelSalaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelSalaMouseExited(evt);
            }
        });

        TextSala1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextSala1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextSala1.setText("SALAS");

        javax.swing.GroupLayout PanelSalaLayout = new javax.swing.GroupLayout(PanelSala);
        PanelSala.setLayout(PanelSalaLayout);
        PanelSalaLayout.setHorizontalGroup(
            PanelSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalaLayout.createSequentialGroup()
                .addComponent(TextSala1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        PanelSalaLayout.setVerticalGroup(
            PanelSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalaLayout.createSequentialGroup()
                .addComponent(TextSala1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelRound2.add(PanelSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 220, -1));

        PanelReserva.setBackground(new java.awt.Color(153, 255, 255));
        PanelReserva.setPreferredSize(new java.awt.Dimension(220, 76));
        PanelReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelReservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelReservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelReservaMouseExited(evt);
            }
        });

        TextReserva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextReserva.setText("RESERVAS");

        javax.swing.GroupLayout PanelReservaLayout = new javax.swing.GroupLayout(PanelReserva);
        PanelReserva.setLayout(PanelReservaLayout);
        PanelReservaLayout.setHorizontalGroup(
            PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReservaLayout.createSequentialGroup()
                .addComponent(TextReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        PanelReservaLayout.setVerticalGroup(
            PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelRound2.add(PanelReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 184, 220, 70));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 430));

        javax.swing.GroupLayout PanelCambiosLayout = new javax.swing.GroupLayout(PanelCambios);
        PanelCambios.setLayout(PanelCambiosLayout);
        PanelCambiosLayout.setHorizontalGroup(
            PanelCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        PanelCambiosLayout.setVerticalGroup(
            PanelCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        panelRound1.add(PanelCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 490, 430));

        FondoPanel.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 430));

        FondoText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo.jpg"))); // NOI18N
        FondoPanel.add(FondoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelSalaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSalaMouseEntered
        PanelSala.setBackground(new Color(51,204,255));
    }//GEN-LAST:event_PanelSalaMouseEntered

    private void PanelSalaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSalaMouseExited
        PanelSala.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_PanelSalaMouseExited

    private void PanelReservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservaMouseEntered
        PanelReserva.setBackground(new Color(51,204,255));
    }//GEN-LAST:event_PanelReservaMouseEntered

    private void PanelReservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservaMouseExited
        PanelReserva.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_PanelReservaMouseExited

    private void PanelReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservaMouseClicked
        initRese();
    }//GEN-LAST:event_PanelReservaMouseClicked

    private void PanelSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSalaMouseClicked
        initSalas();
    }//GEN-LAST:event_PanelSalaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sesion().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel FondoText;
    private javax.swing.JPanel PanelCambios;
    private javax.swing.JPanel PanelReserva;
    private javax.swing.JPanel PanelSala;
    private javax.swing.JLabel TextReserva;
    private javax.swing.JLabel TextSala1;
    private javax.swing.JButton jButton1;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables

    private void initSalas() {
        SalasUsu Sal = new SalasUsu(documento);
        Sal.setSize(750, 430);
        Sal.setLocation(0,0);
        
        PanelCambios.removeAll();
        PanelCambios.add(Sal, BorderLayout.CENTER);
        PanelCambios.revalidate();
        PanelCambios.repaint();
        
    }
    
    private void initRese() {
        ReservasUsu Sal = new ReservasUsu(documento);
        Sal.setSize(750, 430);
        Sal.setLocation(0,0);
        
        PanelCambios.removeAll();
        PanelCambios.add(Sal, BorderLayout.CENTER);
        PanelCambios.revalidate();
        PanelCambios.repaint();
        
    }

    private void initSalas(int documento) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
